GET http://localhost:1234/users/ed7758f1-8575-4873-bffd-42215ef6253e

GET http://localhost:1234/users

GET http://localhost:1234/users?username=jero

POST  https://client-api-dev-qjme.3.us-1.fl0.io/users
Content-Type: application/json

{
    "username": "juanjo_chipy",
    "name": "Jeronimo",
    "lastName": "Chipy",
    "email": "chipyjeronimo@gmail.com",
    "country": "Argentina"
}

PATCH   http://localhost:1234/users/cde3-1049-4b87-8155-be2960cd350f
Content-Type: application/json

{
    "username": "jerojerojerojero"
}
